### ISSUE TITLE
Potential server port mismatch

### ISSUE THREAD

**Issue by inatatsu** [blueperf/acmeair-mainservice-springboot#1]
Hi. The server port in [server.xml](https://github.com/blueperf/acmeair-mainservice-springboot/blob/c27581a6f1317fd221bef85d00d2eefe24e6d0ed/server.xml#L9) is 9080 and [application.properties](https://github.com/blueperf/acmeair-mainservice-springboot/blob/c27581a6f1317fd221bef85d00d2eefe24e6d0ed/src/main/resources/application.properties#L2) is 80. Is this OK? The same mismatch exists in other services.

**Comment by jdmcclur** [comment]
I think what is in the server.xml overrides the application.properties in this case, but I should probably change the application.properties to 9080.

**Comment by jdmcclur** [comment]
Fixed now.
