### ISSUE TITLE
Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean

### ISSUE THREAD

**Issue by desprez** [blueperf/acmeair-mainservice-springboot#2]
Springboot services dont start:

acmeair-mainservice-springboot        | 2019-10-23 15:09:07.797 ERROR 1 --- [ecutor-thread-2] o.s.boot.SpringApplication               : Application run failed
acmeair-mainservice-springboot        |
acmeair-mainservice-springboot        | org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
acmeair-mainservice-springboot        |         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:157) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
acmeair-mainservice-springboot        |         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
acmeair-mainservice-springboot        |         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
acmeair-mainservice-springboot        |         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
acmeair-mainservice-springboot        |         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
acmeair-mainservice-springboot        |         at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
acmeair-mainservice-springboot        |         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
acmeair-mainservice-springboot        |         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
acmeair-mainservice-springboot        |         at com.acmeair.springboot.MainServiceSpringBootApplication.main(MainServiceSpringBootApplication.java:47) [acmeair-mainservice-springboot-2.1.1-SNAPSHOT.spring:na]
acmeair-mainservice-springboot        |         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0]
acmeair-mainservice-springboot        |         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90) ~[na:1.8.0]
acmeair-mainservice-springboot        |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[na:1.8.0]
acmeair-mainservice-springboot        |         at java.lang.reflect.Method.invoke(Method.java:508) ~[na:1.8.0]
acmeair-mainservice-springboot        |         at com.ibm.ws.app.manager.springboot.internal.SpringBootRuntimeContainer.lambda$invokeSpringMain$6(SpringBootRuntimeContainer.java:137) [com.ibm.ws.app.manager.springboot_1.0.33.jar:na]
acmeair-mainservice-springboot        |         at com.ibm.ws.app.manager.springboot.internal.SpringBootRuntimeContainer$$Lambda$10.00000000241FC360.run(Unknown Source) ~[na:na]
acmeair-mainservice-springboot        |         at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239) ~[na:na]
acmeair-mainservice-springboot        |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160) ~[na:1.8.0]
acmeair-mainservice-springboot        |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:1.8.0]
acmeair-mainservice-springboot        |         at java.lang.Thread.run(Thread.java:818) ~[na:2.9 (09-11-2019)]
acmeair-mainservice-springboot        | Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
acmeair-mainservice-springboot        |         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:206) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
acmeair-mainservice-springboot        |         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
acmeair-mainservice-springboot        |         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:154) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
acmeair-mainservice-springboot        |         ... 18 common frames omitted

I'm not familiar with the Springboot 2.0 liberty feature but it seams that servlet container couldn't be found by spring.

**Comment by jdmcclur** [comment]
I can reproduce this. It used to work and now it does not, trying to track down why.

**Comment by jdmcclur** [comment]
I modified the Dockerfiles to be more modern and it works now. Let me know if you have more problems.

**Comment by desprez** [comment]
It works fine : thank you.
I really appreciate the promptness with which you helped me.
